version = 1

[[annotations]]
path = "package.json"
SPDX-FileCopyrightText = "© Fossology contributors"
SPDX-License-Identifier = "FSFAP"

[[annotations]]
path = "package-lock.json"
SPDX-FileCopyrightText = "© Fossology contributors"
SPDX-License-Identifier = "FSFAP"